services:
  - type: web
    name: webinario-sistema
    env: node
    plan: free
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: postgres
    name: postgres
    plan: free
